global-styling:
  css:
    base:
      css/base/base.css: {}
      css/base/buttons.css: {}
      css/base/typography.css: {}
      css/base/utility.css: {}
      https://fonts.googleapis.com/css2?family=VT323&display=swap:
        { type: external, minified: true }

    component:
      css/components/form.css: {}
views:
  css:
    theme:
      css/components/views-exposed-form.css: {}
      css/components/card.css: {}
      css/components/block.css: {}
view-search:
  css:
    layout:
      css/layout/views-search.css: {}
search-api-autocomplete:
  css:
    component:
      css/components/search-api-autocomplete.css: {}
event-full:
  css:
    component:
      css/components/event-full.css: {}
case-study-full:
  css:
    component:
      css/components/case-study-full.css: {}
project-full:
  css:
    component:
      css/components/project-full.css: {}
person-full:
  css:
    component:
      css/components/person-full.css: {}
